MiSeqDjango/MiSeqDjango/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('point_mutation.urls', namespace='point_mutation')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MiSeq_Standalone/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('point_mutation.urls', namespace='point_mutation')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

point_mutation/urls.py
from django.urls import path
from point_mutation import views


app_name = 'point_mutation'
urlpatterns = [
    path('', views.home, name="home"),
    path('point_mutation', views.point_mutation_upload, name='upload'),
    path('point_mutation_upload', views.point_mutation_upload_folder, name='upload_folder'),
    path('point_mutation_folder_upload', views.folder_upload_ajax, name='ajax_upload'),
    path('point_mutation_view', views.point_mutation_view, name='view'),
    path('point_mutation_allele/<miseq>/<oligo_index>/<exp>', views.point_mutation_allele, name='allele'),
    path('point_mutation_summary/<miseq>/<oligo_index>/<exp>/<limit>', views.allele_summary, name='summary'),
    path('point_mutation/summary', views.allele_summary_ajax, name='summary_test')
]

point_mutation/views.py
"""Standard API methods for displaying MiSeq data"""
import re
import zipfile
import tarfile
from django.http import request

from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template import loader

from rest_framework import status
from rest_framework.decorators import api_view

from point_mutation.parsers.crispresso_parser import CrispressoParser
from point_mutation.parsers.indel_parser import IndelParser
from point_mutation.parsers.frequency_parser import FrequencyParser
from point_mutation.discover import DiscoverFolders
from point_mutation.file_uploader import FileUploader


@api_view(['GET']) 
def home(request):
    if request.method == 'GET':
        context = discover_folders('/var/data/uploadedFiles/')

        return render(request, 'index.html', context)

### 
# Home to have extensible folder selection based on discovery of what miseq folders have been added. Docker to have persistant volume using docker compose.
# selecting a folder from home loads miseq view
# upload folders to volume by script (perhaps a UI later, be aware this will take time.)
# title of page to be "Point Mutation - [Folder Name]"
### 


def discover_folders(base_folder_path):

    discover_folders = DiscoverFolders()

    return discover_folders.get_dirs(base_folder_path)

def point_mutation_view(request, file_path):
    context = point_mutation_summary(file_path)

    request.session['data'] = context

    return render(request, 'point_mutation.dj.html', context)
    
@api_view(['GET'])
def point_mutation_allele(request, miseq, oligo_index, exp):

    print('getting indel_parsr')
    indel_parser = IndelParser()

    data = request.session['data']

    max_wells = 384 if data['large_plate'] else 96

    well_num = oligo_index.zfill(2)
    experiments = data['summary'][well_num]['experiments']
    gene = data['summary'][well_num]['gene']
    details = data['summary'][well_num]['details']
    print('getting indel_stats')
    indel_stats = indel_parser.load_directory(data['file_path'], well_num, exp)
    ##designs = data['designs']['summary']['1'][]
    print('got_indel_stats: ')
    print(indel_stats)

    context = data
    context['miseq'] = miseq
    context['oligoIndex'] = oligo_index
    context['selection'] = exp
    context['maxWells'] = max_wells
    context['experiments'] = experiments
    context['gene'] = gene
    context['details'] = details
    context['indelStats'] = indel_stats

    return render(request, 'point_mutation_allele.dj.html', context)

@api_view(['POST'])
def point_mutation_upload(request):
    if request.method == 'POST':

        file_path = request.POST['folderPath'] + request.POST['item'] + '/'

        return point_mutation_view(request, file_path)

@api_view(['GET'])
def point_mutation_upload_folder(request):
    return render(request, 'point_mutation_upload_folder.dj.html')

@api_view(['GET'])
def allele_summary(request, miseq, oligo_index, exp, limit):

    freq_parser = FrequencyParser()

    data = request.session['data']
    well_num = oligo_index.zfill(2)

    crispr = data['summary'][well_num]['crispr']
    allele_freq_data = freq_parser.get_allele_freq_data(data['file_path'], well_num, exp, limit)

    context = {
        'crispr': crispr,
        'data' : allele_freq_data
    }

    return

def allele_summary_ajax(request):
    if request.is_ajax and request.method == 'GET':
        oligo_index = request.GET.get('oligo_index', None)
        exp = request.GET.get('exp', None)
        limit = request.GET.get('limit', None)

        freq_parser = FrequencyParser()

        data = request.session['data']
        well_num = oligo_index.zfill(2)

        crispr = data['summary'][well_num]['crispr'][exp]
        allele_freq_data = freq_parser.get_allele_freq_data(data['file_path'], well_num, exp, limit)
        
        context = {
            'crispr': crispr,
            'data' : allele_freq_data
        }

        return JsonResponse(context, status = 200)

def point_mutation_summary(file_path):
    
    if not file_path:
        file_path = '/home/ubuntu/dev/miseq-standalone/testFiles/Miseq_093/'

    parser = CrispressoParser()
    
    data = {
        'file_path': file_path,
        'summary': {
            '01': {
                'percentages': 'quant_data'
            }
        }
    }

    parser.global_threshold = 1000
    parser.threshold_percent = 5
    data.update(parser.load_directory(file_path))

    return data

def folder_upload_ajax(request):
    try:
     if request.is_ajax and request.method == 'POST':
        path = request.POST["filePath"]
        file = request.FILES.get("file")

        file_uploader = FileUploader()

        file_uploader.handle_files(path, file)

        return JsonResponse({}, status = 200)
    except:
        return JsonResponse({}, status = 400)

point_mutation/templates/browse_point_mutation.dj.html
<!doctype html>
<html lang="en">

<head>
    <title>Browse MiSeq Projects</title>
</head>
<style>

#scroll-y{
    display: block;
    overflow-x: hidden;
    overflow-y: scroll; 
    height: 50vh;
}

</style>

<div class="col-md-8 col-md-offset-2">
    <form id ="geneForm" class="well">
        <fieldset>
            <legend>Search by Gene Symbol</legend>
            <div class="col-md-5">
                <input type="text" class="form-control" name="gene_name" placeholder="Gene Symbol" id="geneName" />
            </div>
            <i id="geneLoading"></i>
        </fieldset>
    </form>
</div>

<div id="geneResultsDiv" class="col-md-8 col-md-offset-2" hidden>
    <table id="geneResultsTable" class="table table-striped" style="table-layout:fixed" align="center">
        <thead>
            <h4 align="center">Search Results</h4>
            <tr>
                <th>Plate Name</th>
                <th>Experiment</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<div class="col-md-8 col-md-offset-2">
    <form class="well">
        <fieldset>
            <legend>Search by MiSeq Name</legend>
            <div class="col-md-5">
                <input type="text" class="form-control" name="miseq_name" placeholder="MiSeq project" id="miseqName" />
            </div>
            <i id="miseqLoading"></i>
        </fieldset>
    </form>
</div>

<div class="col-md-8 col-md-offset-2" id="scroll-y" >
    <table class="table table-striped">
        <thead>
            <h4 align="center">Recently Added <i id="recLoading"></i></h4>
            <tr>
                <th>Name</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for result in miseqs %}
                <tr>
                    <td>      
                        <a class="brand" onclick='loading("rec");' href="{{ baseUrl }}/point_mutation/?miseq={{ result.name}}">
                            {{ result.name }}
                        </a>
                    </td>
                    <td>{{ result.date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script type="text/javascript">

$(".well").submit(function(e) {
    e.preventDefault();
});

$("#miseqName").autocomplete({
    source: function(request, response) {
        $.getJSON("{{ baseUrl }}/api/autocomplete/plates_by_type/",
        {
            term : $('#miseqName').val(),
            type : 'MISEQ',
        }, response);
    },
    minLength: 2,
    select: function(event, ui) {
        loading('miseq');
        window.location.href = "{{ baseUrl }}/point_mutation/" + encodeURI('?miseq=' + ui.item.value);
    },
});

$("#geneName").autocomplete({
    source: function(request, response) {
        $.getJSON("{{ baseUrl }}/api/autocomplete/miseq_gene_symbols/",
        {
            term : $('#geneName').val(),
        }, response);
    },
    minLength: 2,
    select: function(event, ui) {
        $.ajax({
            url: '{{ baseUrl }}/api/miseq_exp_parent/',
            type: "GET",
            contentType: 'application/json; charset=utf-8',
            data: {
                term: ui.item.value, 
            },
            success: function(result){
                $('#geneResultsDiv').show();
                modifyResultsTable(result);
            },
            error: function() {
                console.log("Failed to retrieve data");
                $('#resultsDiv').hide();
            }
        });
    },
});

function modifyResultsTable(res) {
    var rows = '';
    for (var exp = 0; exp < res.length; exp++) {
        var data = res[exp];
        console.log(data)
        var link = '{{ baseUrl }}/point_mutation/")' + encodeURI('?miseq=' + data.plate + '&experiment=' + data.name);
        var aPlate = '<a class="brand" href="' + link + '" onclick=\'loading("gene");\'>' + data.plate + '</a>';
        
        var row = '<tr><td>' + aPlate + '</td><td>' + data.name + '</td><td>' + data.date + '</td></tr>';
        rows = rows.concat(row);
    }
    $('#geneResultsTable tbody').html(rows);
}

function loading(sect) {
    $('#' + sect + 'Loading').addClass('glyphicon glyphicon-refresh spinning');
}

</script>

point_mutation/templates/create_miseq_plate.dj.html
<meta http-equiv="Content-Language" content="en">
<style>

</style>

{% include 'plate_grid_view.html' rows = 8 columns = 12 letters_on = "row" row_pixel = 50 column_pixel = 50 %}
<div id="response" class="alert"></div>
<div class="page-header">
  <h1>Create MiSEQ Plate</h1>
</div>
<div class="container">
    <div id="plateDetails">
        <h3>Plate Details</h3>
        <table class="table table-striped">
            <tr>
                <td>
                    <label>Name: </label>
                </td>
                <td>
                    <div class="col-md-4">
                        <input type="text" class="form-control" id="plateName" oninput="updatePlateName(0);">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label>384 wells?</label>
                </td>
                <td>
                    <input type="checkbox" id="largeBox" value="1">
                </td>
            </tr>
        </table>
    </div>
    <h3>Parent Plates</h3>
    <div class="row">
        <div class="col-md-2">
            <label>Parent Plate Name:</label>
        </div>
        <div class="col-md-3">
            <input type="text" class="form-control" id="parentPlate">
        </div>
        <div class="col-md-1">
            <button class="btn btn-warning" id="addPlate"><i class="glyphicon glyphicon-plus"></i> Add</button>
        </div>
    </div>
    <br>
</div>

<div id="miseq">
    <table id="parentCollection" class="table table-striped" hidden>
        <tr>
            <th>
                Name
            </th>
            <th>
                Type
            </th>
            <th>
                Details
            </th>
            <th>
                Clear
            </th>
        </tr>
    </table>
    <br>
<div>

<div id="plateVisual">
    <div id="plateRow" class="col-md-12">
        <div class="col-md-4">
            <h4>Parent Plate: </h4>
            <select id="freezeName" class="btn btn-default">
                <option value="-">Parent Plate</option>
            </select>
        </div>
        <div class="col-md-3" id="fpQuadDiv">
            <h4>Plate:</h4>
            <select id="fpQuad" class="btn btn-default">
                <option value="A_1" selected="selected">1-96 (A01-H12)</option>
                <option value="A_13">97-192 (A13-H24)</option>
                <option value="I_1">193-288 (I1-P12)</option>
                <option value="I_13">289-384 (I13-P24)</option>
            </select>           
        </div>
        <div class="col-md-3">
            <h4>Direction: </h4>
            <button id="directionSwitch" class="btn btn-primary"><i id="directionIcon" class="glyphicon glyphicon-arrow-down"></i></button>
        </div>
        <div id="firstSplit" class="col-md-12"></div>
            <div class="row col-md-12">
                <div class="col-md-4">
                    <h4>MiSEQ Plate: </h4>
                    <h4 id="miseqName">MiSEQ Plate Name</h4>
                </div>
                <div class="col-md-4">
                    <h4>Process:</h4>
                    <select id="process" class="btn btn-default">
                        <option value="nhej" selected="selected">No Template (NHEJ/WT only)</option>
                        <option value="oligo">Oligo</option>
                        <option value="vector">Vector</option>
                    </select>
                </div>
                <div id="quadDiv" class="col-md-4">
                    <h4>Plate:</h4>
                    <select id="quad" class="btn btn-default">
                        <option value="A_1" selected="selected">1-96 (A01-H12)</option>
                        <option value="A_13">97-192 (A13-H24)</option>
                        <option value="I_1">193-288 (I1-P12)</option>
                        <option value="I_13">289-384 (I13-P24)</option>
                    </select>
                </div>

            </div>
        <div id="secondSplit" class="col-md-12"></div>
    </div>
    <div class="row">
        <button type="button" class="btn btn-danger" onclick="clearPlate();">
            Clear
        </button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirmationModal" onclick="populateModal();">
            Submit
        </button>
    </div>
</div>

<div id="confirmationModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="col-md-12">
                    <h4 class="modal-title col-md-4" id="modalMiseqName">MiSEQ Plate: </h4>
                    <div class="col-md-6">
                        <input type="text" class="form-control" id="modalName">
                    </div>
                </div>
            </div>
            <div class="modal-body" id="modalBody">
                <div class="panel-group" id="accordion"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="updatePlateName(1);">Close</button>
                <button type="button" class="btn btn-primary" onclick="submit();">Submit</button>
            </div>
        </div>
    </div>
</div>

{% include 'plateupload/rearray_interface.html' %}

<script>

$(function () {
    var isMouseDown = false;
    var startIndex;

    $("#secondSplit")
        .mousedown(function(evt) {
            startIndex = highlighter(evt.target);
            isMouseDown = true;
            console.log("Down.");
        })
        .mouseover(function(evt) {
            if (isMouseDown == true){
                highlighter(evt.target, startIndex);
            }
        });

    $('body').mouseup(function(evt) {
        if (isMouseDown == true) {
            console.log("Up.");
            isMouseDown = false;
            $('.selecting').toggleClass('selecting selected');
            d3.selectAll('.selected').style('fill', colourHash['green']);
            var key = $('#freezeName').val();
            if (key != '-') {
                console.log('Triggered - body up');
                var label = quadLabels[$('#quad').val()];
                if (relationalData[key] == null) {
                    relationalData[key] = {
                        wells : { },
                        process : $('#process').val(),
                    }
                } 
                var plateDetails = relationalData[key];
                plateDetails.process = $('#process').val(); //In case of change
                plateDetails.wells[label] = { };

                $('.miWell.selected').map(function() { return trackWells(key, label, this); });
                $('.fpWell.selected').map(function() { return checkTile(); } )
            }
        }
    });
});

function trackWells(key, section, well) {
    var freezer = relationalData[key].wells[section];
    freezer[$(well).parent()[0].id] = well.value;
    relationalData[key].wells[section] = freezer;
}

function submit() {
    var plateName = $('#modalName').val();
    var largePlate = $('#largeBox:checked').val() || 0;
    var container = {
        name            : plateName,
        large           : largePlate,
        data            : relationalData
    };
    var data = JSON.stringify(container);
    if (plateName != '') {
        $('#response').attr('class','alert');
        $.ajax({
            url: '{{ baseUrl }}/api/miseq_plate/',
            type: 'POST',
            dataType: 'JSON',
            data: {
                json: data
            },
            success: function(result) {
                $('#response').addClass('alert-success');
                $('#response').text('Created MiSeq Plate: ' + result.name + ' with id: ' + result.id);
                closeModal();
            },
            error: function(err) {
                $('#response').addClass('alert-danger');
                $('#response').text('Failed to create MiSeq plate: ' + err.responseJSON.error);
                closeModal();
            }
        });
    }
}

function clearPlate() {
    var rects = $('rect').not('.invalid');
    $('.miWell').map(function() { resetMiseqText(this); });
    d3.selectAll(rects).style('fill', 'white');
    d3.selectAll(rects).classed('selected', false);
    var name = $('#freezeName').val();
    relationalData[name] = {};
}



function findFpWells() {
    var parentChildMapping = {};

    var plateDetails = relationalData[$('#freezeName').val()];
    if (plateDetails === undefined) {
        return;
    }
    var quadrantLabel = quadLabels[$('#quad').val()];
    var quadrantWellData = plateDetails.wells[quadrantLabel];

    for (var childWell in quadrantWellData) {
        parentChildMapping[quadrantWellData[childWell]] = childWell; //Parent => Child
    }

    return parentChildMapping;
}

function populateModal(){
    $('#modalName').val($('#plateName').val());
    $('#accordion').html("");
    var freezerPlates = Object.keys(relationalData);

    var panelOpening = '<div class="panel panel-default">';
    var panelClosing = '</div>';
    
    var header = '<div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse';
    var headerClosing = '</a></h4></div>';
    
    var bodyOpen = '<div id="collapse';
    var bodyClass = '" class="panel-collapse collapse"><div class="panel-body"><p>';
    var bodyClosing = '</p></div></div>';

    
    for (var key = 0; key < freezerPlates.length; key++) {
        var fpName = freezerPlates[key];
        var fpDetails = relationalData[fpName].wells;
        var process = relationalData[fpName].process;

        var wellParagraph = "";

        var quads = Object.keys(fpDetails);

        for (var quad = 0; quad < quads.length; quad++) {
            var quadDetails = fpDetails[quads[quad]];

            var wellKeys = Object.keys(quadDetails);
            var plateStructure = {};
        
            for (var well = 0; well < wellKeys.length; well++) {
                var miseqWellName = wellKeys[well];
                var fpWellName = quadDetails[miseqWellName];
                var row = miseqWellName.charAt(0);
                if (!(row in plateStructure)) {
                    plateStructure[row] = [];
                    plateStructure[row].push(fpWellName + " &rarr; " + miseqWellName);
                } else {
                    plateStructure[row].push('</br>' + fpWellName + " &rarr; " + miseqWellName);
                }
            }
            var rows = Object.keys(plateStructure);

            for (var row = 0; row < rows.length; row++) {
                wellParagraph += plateStructure[rows[row]].toString() + '</br>';
            }
        }
        var panelHeader = header + fpName + '">' + fpName + '&nbsp ~ &nbsp Process: ' + process + headerClosing;
        var panelBody = bodyOpen + fpName + bodyClass + wellParagraph + bodyClosing;
        var panel = panelOpening + panelHeader + panelBody + panelClosing;
        $("#accordion").append(panel);
    }
}

function showPlateHistory(parentName) {
    var parentDetails = relationalData[parentName];
    var quadrantLabel = quadLabels[$('#quad').val()];
    var quadrantWells = parentDetails.wells[quadrantLabel];
    var miWells = Object.keys(quadrantWells);
    console.log(miWells);
    wellHistory(0);
    wellHistory(1);
    for (var mi = 0; mi < miWells.length; mi++) {
        var fpID = $('#firstSplit #' + quadrantWells[miWells[mi]] + ' .square')[0].id.split('_')[1];
        var miID = $('#secondSplit #' + miWells[mi] + ' .square')[0].id.split('_')[1];
        tracking(miID, fpID);
    }
}

function wellHistory(plate) {
    var fpRelations = findFpWells(relationalData);
    if (fpRelations === undefined) {
        return;
    }
    var fpWells = Object.keys(fpRelations);
    $('.square').removeClassesExcept('square fpWell miWell');

    fpWells.forEach(function(fp) {
        d3.select('#firstSplit #' + fp + ' rect').classed('selected', true);
        d3.select('#secondSplit #' + fpRelations[fp] + ' rect').classed('selected', true);
    });
    d3.selectAll('.selected').style('fill', colourHash['green']);

    return;
}
</script>

point_mutation/templates/index.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
    <title>Point Mutation</title>
</head>

{% include "./navbar.dj.html" %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/d3.min.js' %}"></script>
<script src="{% static 'js/d3-tip.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>

<link rel="icon" href="{% static 'favicon.ico' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'css/ui-lightness/jquery-ui-1.12.0.custom.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-select.min.css' %}"></link>


<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.qtip.min.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bxslider.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bootgrid.min.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.custom.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'css/lims2.css' %}"></link>

    <body>
        <div id="main" class="container">
        {% if folder_list %}
            <div style="text-align:center">
                <h2>Select Folder</h2>    
            </div>

            <div class="row grid-container">

                {% for item in folder_list %}
                    <div class="grid-item">
                        <form class="column" action="{% url 'point_mutation:upload' %}" method="POST">
                            <input type="hidden" name="folderPath" value={{ folder_path }} />
                            <input type="hidden" name="item" value={{ item }} />
                            <input id="submit" type="submit" class="button" value="{{ item }}"/>
                        </form>
                    </div>

                {% endfor %}
            </div>
        
        {% else %}
            <div style="text-align:center">
                <h2>Upload folder to {{ folder_path }} to select for viewing.</h2>
                <button type="button" value="Upload" href="{% url 'point_mutation:upload_folder' %}">Upload</button>
            </div>
        {% endif %}
        </div> 
    </body>
</html>

<style>
    .button {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
    }

    .container {
        padding-top: 50px;
    }

    .grid-container {
        width: 100%;
        display: grid;
        grid-template-columns: repeat(5, 1fr);
    }

    .grid-item {
        border: none;
        padding: 5px;
        display: grid;
        place-items: center;
    }

    .row::before {
        content: none;
    }

    .row::after {
        content: none;
    }

    .container::before {
        content: none;
    }

    .container::after {
        content: none;
    }
</style>

point_mutation/templates/miseq_alleles_frequency.dj.html
<style>

.sequence {
    width: 400px;
    white-space: nowrap;
    font-family: "Lucida Console", Monaco, monospace;
    overflow-x: hidden;
}

.target :not(.baseSwitch) {
    background-color: #0A606D; /* Blue-Grey */
    color: white;
}

.possibleTarget :not(.baseSwitch) {
    background-color: #FF9E00; /* Orange */
    color: black;
}

.base- {
    background-color: #661010 !important; /* Red */
    color: white !important;
}

.insertion:not(.baseSwitch) {
    background-color: #26C485 !important; /* Green */
    color: black;
}

.mutation:not(.baseSwitch) {
    background-color: #F61067 !important; /* Pink */
    color: white;
}

.insertion, .mutation {
    font-weight: bold;
}

.mutation {
    text-decoration: underline;
}

</style>

<script type="text/javascript" charset="utf-8">

function highlightBases(seq, crisprData, ref, quality) {
    var formattedSequence = "";
    var start = -1;
    var accuracy = -1;

    if (crisprData.crispr != "") {
        start = seq.indexOf(crisprData.crispr);
        if (start == -1) {
            start = seq.indexOf(crisprData.rev_crispr);
        }

        if (start == -1) {
            if (ref) {
                start = ref.indexOf(crisprData.crispr);
            }
            if (start == -1 || start > crisprData.position + 5 || start < crisprData.position - 5) {
                console.log('No match');
                start = crisprData.position;
            }
        } else {
            accuracy = 0;
        }
    } else {
        console.log("No crispr found");
        console.log(crisprData);
    }
    
    var mutations = {
        A: ['C','G','T'],
        C: ['A','G','T'],
        T: ['A','C','G'],
        G: ['A','C','T']
    }; //Ignore - and Ns
    var deletionOffset = 0;
    var insertionOffset = 0;

    for (var base = 0; base < seq.length; base++) {
        var letter = seq[base];

        var crisprLoc = start;
        if (accuracy == -1) {
            crisprLoc += insertionOffset;
        }

        var front = "";
        if (base == crisprLoc) {
            if (accuracy == 0) {
                front = '<span class="target">';
                insertionOffset = 0;
            } else {
                front = '<span class="possibleTarget">';
            }
        }

        var classStr = 'baseSwitch ';
        if (ref) {
            if (ref[base] == '-') {
                classStr += 'insertion ';
                insertionOffset++;
            } else {
                if (mutations[ref[base]].indexOf(letter) != -1) {
                    classStr += 'mutation ';
                }
            }
        }

        if (letter == '-') {
            classStr += 'base- ';
            deletionOffset++;
        } else {
            if (quality) {
                classStr += qualityConversion(quality[base - deletionOffset]);
            }
        }

        var back = "";
        if (base == start + crisprData.crispr.length + insertionOffset - 1) {
            back = "</span>";
        }

        var format = front + '<span class="' + classStr + '">' + letter + '</span>' + back;
        formattedSequence += format;
    }

    return formattedSequence;
}

function qualityConversion(qualityLetter) {
    if (qualityLetter) {
        var score = qualityLetter.charCodeAt() - 33;
        var classRank = '';
        switch (true) {
            case (score <= 10):
                classRank = 'lowQS';
                break;
            case (score <= 20):
                classRank = 'medQS';
                break;
            default:
                break;
        }
        return classRank;
    }
    return;
}

</script>

point_mutation/templates/miseq_quadrant_table.dj.html
<svg width="520" height="320">
    <rect id="firstQuad" class="quad" x="5" y="5" width="250" height="150" stroke="black" fill="white"/>
    <text x="130" y="80" alignment-baseline="middle" text-anchor="middle" class="lb-md">1 - 96</text>
    <rect id="secondQuad" class="quad" x="265" y="5" width="250" height="150" stroke="black" fill="white"/>
    <text x="390" y="80" alignment-baseline="middle" text-anchor="middle" class="lb-md">97 - 192</text>
    <rect id="thirdQuad" class="quad" x="5" y="165" width="250" height="150" stroke="black" fill="white"/>
    <text x="130" y="240" alignment-baseline="middle" text-anchor="middle" class="lb-md">193 - 288</text>
    <rect id="fourthQuad" class="quad" x="265" y="165" width="250" height="150" stroke="black" fill="white"/>
    <text x="390" y="240" alignment-baseline="middle" text-anchor="middle" class="lb-md">289 - 384</text>
</svg>

point_mutation/templates/navbar.dj.html
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="nav navbar-brand" href="{% url 'point_mutation:home' %}">Home</a>
    </div>
    <div class="navbar-body">
        <a class="nav navbar-brand" href="{% url 'point_mutation:upload_folder' %}">Upload</a>
    </div>
  </div>
</div>

<style>
  .navbar-body {
    margin-bottom: 5px;
  }
</style>